spring.application.name=dgac-ms-reportes

# Puerto dinámico para la nube, y 8090 por defecto en tu entorno local
server.port=${PORT:8090}

# Conexión a la base de datos de Neon parametrizada
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-young-thunder-aq0arqn7-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_0VRNzvtkyf8H}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect